# Generated by Django 6.1.1 on 2026-09-05 16:57

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('pillar', models.CharField(choices=[('IMMIGRATION', 'Imigração e Regularização'), ('EDUCATION', 'Estudo e Educação'), ('NATIONALITY', 'Nacionalidade e Naturalização'), ('COMMUNITY', 'Comunidades e Apoio aos Haitianos')], db_index=True, max_length=30)),
                ('document_type', models.CharField(choices=[('LAW', 'Lei Federal'), ('DECREE', 'Decreto Presidencial'), ('PORTARIA', 'Portaria Ministerial / Interministerial'), ('GUIDE', 'Guia / Manual Oficial'), ('CARTILHA', 'Cartilha de Orientação'), ('FAQ', 'Perguntas Frequentes Homologadas')], default='GUIDE', max_length=30)),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='sources.officialsource')),
            ],
            options={
                'verbose_name': 'Documento de Conhecimento',
                'verbose_name_plural': 'Documentos de Conhecimento',
                'ordering': ['pillar', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(default=dict, help_text='Metadados contextuais (título do documento, artigo, pilar, URL)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgedocument')),
            ],
            options={
                'verbose_name': 'Fragmento Vetorial (Chunk)',
                'verbose_name_plural': 'Fragmentos Vetoriais (Chunks)',
                'ordering': ['document', 'chunk_index'],
            },
        ),
    ]
