# Generated by Django 6.1.1 on 2026-09-05 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('partner_type', models.CharField(choices=[('LEGAL', 'Assistência Jurídica Gratuita'), ('RECEPTION', 'Acolhimento e Assistência Social'), ('EDUCATIONAL', 'Cursos e Educação'), ('COMMUNITY', 'Associação Comunitária')], db_index=True, default='RECEPTION', max_length=30)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=10)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('languages_supported', models.JSONField(default=list, help_text="Lista de códigos de idiomas atendidos, ex: ['ht', 'fr', 'pt', 'en', 'es']")),
                ('services_description', models.TextField(blank=True, default='')),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parceiro Comunitário / Órgão de Apoio',
                'verbose_name_plural': 'Diretório de Parceiros Comunitários',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhitelistDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Domínio Homologado',
                'verbose_name_plural': 'Domínios Homologados (Whitelist)',
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='OfficialSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('pillar', models.CharField(choices=[('IMMIGRATION', 'Imigração e Regularização'), ('EDUCATION', 'Estudo e Educação'), ('NATIONALITY', 'Nacionalidade e Naturalização'), ('COMMUNITY', 'Comunidades e Apoio aos Haitianos')], db_index=True, default='IMMIGRATION', max_length=30)),
                ('authority_level', models.CharField(default='FEDERAL', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='sources.whitelistdomain')),
            ],
            options={
                'verbose_name': 'Fonte Oficial',
                'verbose_name_plural': 'Fontes Oficiais',
                'ordering': ['pillar', 'name'],
            },
        ),
    ]
