# Generated by Django 6.1.1 on 2026-09-14 14:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ui_language', models.CharField(choices=[('ht', 'Kreyòl Ayisyen (Crioulo Haitiano)'), ('fr', 'Français (Francês)'), ('es', 'Español (Espanhol)'), ('en', 'English (Inglês)'), ('pt', 'Português (Brasil)')], db_index=True, default='pt', help_text='Código ISO do idioma da interface e respostas', max_length=10)),
                ('primary_pillar', models.CharField(blank=True, choices=[('IMMIGRATION', 'Imigração e Regularização'), ('EDUCATION', 'Estudo e Educação'), ('NATIONALITY', 'Nacionalidade e Naturalização'), ('COMMUNITY', 'Comunidades e Apoio aos Haitianos')], db_index=True, help_text='Pilar temático principal da sessão se selecionado', max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadados de acesso anônimos (ex: canal PWA, user-agent)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sessão de Atendimento',
                'verbose_name_plural': 'Sessões de Atendimento',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('USER', 'Usuário'), ('ASSISTANT', 'Assistente MigrantIA'), ('SYSTEM', 'Sistema')], db_index=True, default='USER', max_length=20)),
                ('content', models.TextField(help_text='Conteúdo textual da mensagem (higienizado contra PII/LGPD)')),
                ('sources_cited', models.JSONField(blank=True, default=list, help_text='Lista de fontes oficiais e links governamentais citados')),
                ('golden_rule_triggered', models.BooleanField(default=False, help_text='Indica se a resposta ativou a salvaguarda da Regra de Ouro (sem evidências)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Métricas de tempo de resposta, step RAG e tokens')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'verbose_name': 'Mensagem do Chat',
                'verbose_name_plural': 'Mensagens do Chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.SmallIntegerField(choices=[(1, 'Útil / Positivo'), (-1, 'Não Útil / Negativo')], help_text='+1 para útil, -1 para não útil')),
                ('reason', models.CharField(blank=True, choices=[('INACCURATE', 'Informação Incorreta ou Imprecisa'), ('UNHELPFUL', 'Não Respondeu à Dúvida'), ('OUTDATED', 'Informação Desatualizada'), ('LANGUAGE_ERROR', 'Problema de Tradução ou Idioma'), ('OTHER', 'Outro Motivo')], help_text='Motivo categorizado em caso de feedback negativo', max_length=30, null=True)),
                ('comment', models.TextField(blank=True, default='', help_text='Comentário livre ou sugestão do usuário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chat.chatmessage')),
            ],
            options={
                'verbose_name': 'Avaliação da Mensagem',
                'verbose_name_plural': 'Avaliações das Mensagens',
                'ordering': ['-created_at'],
            },
        ),
    ]
