# Generated by Django 6.1.1 on 2026-10-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_security_threat',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica se a mensagem é ou responde a uma ameaça de segurança / violação / injeção de prompt'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='security_threat_reason',
            field=models.CharField(blank=True, db_index=True, help_text='Motivo categorizado da violação ou suspeita de segurança (ex: prompt_injection_detected, canary_leakage)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Métricas de tempo de resposta, step RAG, tokens e auditoria'),
        ),
    ]
